/**
 * nlpapiv2
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveNlpApiClient);
  }
}(this, function(expect, CloudmersiveNlpApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveNlpApiClient.LanguageTranslationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LanguageTranslationApi', function() {
    describe('languageTranslationTranslateDeuToEng', function() {
      it('should call languageTranslationTranslateDeuToEng successfully', function(done) {
        //uncomment below and update the code to test languageTranslationTranslateDeuToEng
        //instance.languageTranslationTranslateDeuToEng(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('languageTranslationTranslateEngToDeu', function() {
      it('should call languageTranslationTranslateEngToDeu successfully', function(done) {
        //uncomment below and update the code to test languageTranslationTranslateEngToDeu
        //instance.languageTranslationTranslateEngToDeu(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('languageTranslationTranslateEngToFra', function() {
      it('should call languageTranslationTranslateEngToFra successfully', function(done) {
        //uncomment below and update the code to test languageTranslationTranslateEngToFra
        //instance.languageTranslationTranslateEngToFra(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('languageTranslationTranslateEngToRus', function() {
      it('should call languageTranslationTranslateEngToRus successfully', function(done) {
        //uncomment below and update the code to test languageTranslationTranslateEngToRus
        //instance.languageTranslationTranslateEngToRus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('languageTranslationTranslateFraToEng', function() {
      it('should call languageTranslationTranslateFraToEng successfully', function(done) {
        //uncomment below and update the code to test languageTranslationTranslateFraToEng
        //instance.languageTranslationTranslateFraToEng(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('languageTranslationTranslateRusToEng', function() {
      it('should call languageTranslationTranslateRusToEng successfully', function(done) {
        //uncomment below and update the code to test languageTranslationTranslateRusToEng
        //instance.languageTranslationTranslateRusToEng(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
