/**
 * nlpapiv2
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExtractEntitiesRequest', 'model/ExtractEntitiesResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ExtractEntitiesRequest'), require('../model/ExtractEntitiesResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveNlpApiClient) {
      root.CloudmersiveNlpApiClient = {};
    }
    root.CloudmersiveNlpApiClient.ExtractEntitiesApi = factory(root.CloudmersiveNlpApiClient.ApiClient, root.CloudmersiveNlpApiClient.ExtractEntitiesRequest, root.CloudmersiveNlpApiClient.ExtractEntitiesResponse);
  }
}(this, function(ApiClient, ExtractEntitiesRequest, ExtractEntitiesResponse) {
  'use strict';

  /**
   * ExtractEntities service.
   * @module api/ExtractEntitiesApi
   * @version 2.1.1
   */

  /**
   * Constructs a new ExtractEntitiesApi. 
   * @alias module:api/ExtractEntitiesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the extractEntitiesPost operation.
     * @callback module:api/ExtractEntitiesApi~extractEntitiesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractEntitiesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract entities from string
     * Extract the named entitites from an input string.
     * @param {module:model/ExtractEntitiesRequest} value Input string
     * @param {module:api/ExtractEntitiesApi~extractEntitiesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractEntitiesResponse}
     */
    this.extractEntitiesPost = function(value, callback) {
      var postBody = value;

      // verify the required parameter 'value' is set
      if (value === undefined || value === null) {
        throw new Error("Missing the required parameter 'value' when calling extractEntitiesPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Apikey'];
      var contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json'];
      var returnType = ExtractEntitiesResponse;

      return this.apiClient.callApi(
        '/nlp-v2/extract-entities', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
